"""Knowledge base generators: kb/ working notes for the site repo.

Builders only — every function here RETURNS (repo-relative path, content);
publish.py is the only module that writes to the site repo or runs git.

  daily_ledger  deterministic (zero LLM) daily record: every curation
                completed that day, the day's best uncurated clusters,
                and the day's ingest activity. Text + links only; never
                archive_url; never images.
  trends        Sonnet ("deep" tier) rolling update of kb/trends.md,
                through the normal adapter + spend caps.
  backfill      daily_ledger over a historical date range.
"""

from __future__ import annotations

import datetime
import json
import sqlite3
from typing import Dict, Optional, Tuple

from .publish import _ARCHIVE_RE, no_archive

TRENDS_PATH = "kb/trends.md"
_CHANGELOG_MARKER = "<!-- signal:changelog -->"

TRENDS_SCHEMA = {
    "type": "object",
    "properties": {
        "trends_md": {"type": "string"},
        "changes": {"type": "string"},
    },
    "required": ["trends_md", "changes"],
    "additionalProperties": False,
}

SYSTEM_TRENDS = (
    "You maintain 'kb/trends.md', a rolling working document tracking the "
    "durable trendlines in technology + AI for a senior engineer's personal "
    "knowledge base. You receive the current document, the latest weekly "
    "digest, and the most recent top curations. Rewrite the document: keep "
    "trends that still hold, update ones that moved, retire dead ones into "
    "a short 'Retired' section, and add genuinely new trendlines. Dense, "
    "factual, link-bearing markdown; ## sections; no H1; no archive.* "
    "links. Also return 'changes': one sentence describing this update. "
    "Respond ONLY with JSON matching the provided schema."
)


def readme() -> Tuple[str, str]:
    return "kb/README.md", (
        "# Signal knowledge base\n\n"
        "Unpublished working notes, generated by the Signal pipeline. "
        "Text and links only — no images, no archive.* URLs.\n\n"
        "- `days/` — one deterministic ledger per weekday: every curation "
        "completed that day, the day's best uncurated clusters, and ingest "
        "activity. Zero LLM involvement.\n"
        "- `trends.md` — a rolling, model-maintained view of the durable "
        "trendlines, updated weekly.\n\n"
        "Nothing in this directory is rendered on the site.\n"
    )


def _day_bounds(date: datetime.date) -> Tuple[str, str]:
    start = datetime.datetime(date.year, date.month, date.day,
                              tzinfo=datetime.timezone.utc)
    return start.isoformat(), (start + datetime.timedelta(days=1)).isoformat()


def _coerce_date(date) -> datetime.date:
    if isinstance(date, datetime.date):
        return date
    return datetime.date.fromisoformat(str(date))


def daily_ledger(conn: sqlite3.Connection, cfg,
                 date) -> Tuple[str, str]:
    """Deterministic markdown ledger for one day. (relpath, content)."""
    date = _coerce_date(date)
    since, until = _day_bounds(date)
    lines = ["# Signal ledger — %s" % date.isoformat(), ""]

    cur_rows = conn.execute(
        "SELECT c.id, c.title, cu.relevance_score, cu.why_it_matters, "
        "cu.notes, a.source_url, a.read_url "
        "FROM curations cu JOIN clusters c ON c.id=cu.cluster_id "
        "LEFT JOIN articles a ON a.cluster_id=cu.cluster_id "
        "WHERE cu.status='done' AND cu.skip=0 "
        "AND cu.curated_at >= ? AND cu.curated_at < ? "
        "ORDER BY cu.relevance_score DESC, cu.curated_at",
        (since, until),
    ).fetchall()
    skipped = conn.execute(
        "SELECT COUNT(*) FROM curations "
        "WHERE ((status='done' AND skip=1) OR status='skipped') "
        "AND curated_at >= ? AND curated_at < ?",
        (since, until),
    ).fetchone()[0]

    lines.append("## Curated (%d done, %d skipped)" % (len(cur_rows), skipped))
    lines.append("")
    if not cur_rows:
        lines.append("No curations completed.")
        lines.append("")
    for r in cur_rows:
        source_url = no_archive(r["source_url"])
        read_url = no_archive(r["read_url"])
        link = source_url or read_url or ""
        title = "[%s](%s)" % (r["title"], link) if link else r["title"]
        lines.append("### %s — %d/10" % (title, r["relevance_score"] or 0))
        if r["why_it_matters"]:
            lines.append("")
            lines.append(r["why_it_matters"])
        notes = json.loads(r["notes"] or "[]")
        if notes:
            lines.append("")
            lines.append("Notes: " + " · ".join(notes))
        link_bits = []
        if source_url:
            link_bits.append("[source](%s)" % source_url)
        if read_url and read_url != source_url:
            link_bits.append("[free read](%s)" % read_url)
        surfs = conn.execute(
            "SELECT s.url, s.points, src.name "
            "FROM surfaces s JOIN sources src ON src.id=s.source_id "
            "WHERE s.cluster_id=? "
            "ORDER BY s.points IS NULL, s.points DESC LIMIT 6",
            (r["id"],),
        ).fetchall()
        for s in surfs:
            url = no_archive(s["url"])
            if not url:
                continue
            label = s["name"]
            if s["points"] is not None:
                label = "%s (%d)" % (label, s["points"])
            link_bits.append("[%s](%s)" % (label, url))
        if link_bits:
            lines.append("")
            lines.append("Links: " + " · ".join(link_bits))
        lines.append("")

    unc = conn.execute(
        "SELECT c.title, c.canonical_url, c.score, c.surface_count "
        "FROM clusters c "
        "WHERE c.first_seen >= ? AND c.first_seen < ? "
        "AND c.score IS NOT NULL "
        "AND NOT EXISTS (SELECT 1 FROM curations cu "
        "  WHERE cu.cluster_id=c.id AND cu.status='done') "
        "ORDER BY c.score DESC LIMIT 15",
        (since, until),
    ).fetchall()
    lines.append("## Top uncurated (%d)" % len(unc))
    lines.append("")
    if not unc:
        lines.append("None scored.")
        lines.append("")
    for r in unc:
        url = no_archive(r["canonical_url"])
        title = "[%s](%s)" % (r["title"], url) if url else r["title"]
        lines.append("- %s — score %.1f, %d surface(s)"
                     % (title, r["score"] or 0.0, r["surface_count"]))
    if unc:
        lines.append("")

    ingest = conn.execute(
        "SELECT ts, message FROM health WHERE job='ingest' "
        "AND level='info' AND ts >= ? AND ts < ? ORDER BY id",
        (since, until),
    ).fetchall()
    lines.append("## Ingest (%d run(s))" % len(ingest))
    lines.append("")
    if not ingest:
        lines.append("No ingest activity recorded.")
    for r in ingest:
        lines.append("- %s — %s" % (r["ts"][11:16], r["message"]))
    lines.append("")

    return "kb/days/%s.md" % date.isoformat(), "\n".join(lines)


def backfill(conn: sqlite3.Connection, cfg, since) -> Dict[str, str]:
    """daily_ledger for every date from `since` through yesterday."""
    start = _coerce_date(since)
    end = datetime.date.today() - datetime.timedelta(days=1)
    writes: Dict[str, str] = {}
    d = start
    while d <= end:
        rel, content = daily_ledger(conn, cfg, d)
        writes[rel] = content
        d += datetime.timedelta(days=1)
    return writes


def _split_changelog(text: str) -> Tuple[str, str]:
    """(body, existing changelog lines) — the changelog block is managed
    deterministically here, never by the model."""
    if _CHANGELOG_MARKER in text:
        body, tail = text.split(_CHANGELOG_MARKER, 1)
        log = tail.split("## Changelog", 1)
        return body.rstrip(), (log[1].strip() if len(log) > 1 else "")
    return text.rstrip(), ""


def trends(conn: sqlite3.Connection, cfg) -> Optional[Tuple[str, str]]:
    """Rolling Sonnet update of kb/trends.md. Returns (relpath, content) or
    None when there is nothing to update from. Spends via the adapter."""
    import os
    import pathlib

    from . import db as db_mod
    from .llm import LLMError, SpendCapExceeded, adapter

    current = ""
    repo_raw = cfg.site.get("repo")
    if repo_raw:
        p = pathlib.Path(os.path.expanduser(repo_raw)) / TRENDS_PATH
        try:
            current = p.read_text()
        except OSError:
            current = ""
    body, old_log = _split_changelog(current)

    weekly = conn.execute(
        "SELECT period_key, title, body_md FROM digests WHERE kind='weekly' "
        "ORDER BY period_key DESC LIMIT 1"
    ).fetchone()
    week_since = (
        datetime.datetime.now(datetime.timezone.utc)
        - datetime.timedelta(days=7)
    ).isoformat()  # Python ISO bound — datetime('now') compares wrong vs 'T'
    picks = conn.execute(
        "SELECT c.title, cu.relevance_score, cu.why_it_matters, cu.summary "
        "FROM curations cu JOIN clusters c ON c.id=cu.cluster_id "
        "WHERE cu.status='done' AND cu.skip=0 AND cu.curated_at >= ? "
        "ORDER BY cu.relevance_score DESC LIMIT 20",
        (week_since,),
    ).fetchall()
    if weekly is None and not picks:
        print("kb trends: no digest or recent curations — skipping")
        return None

    prompt_parts = ["CURRENT TRENDS DOCUMENT:\n%s"
                    % (body or "(empty — first run)")]
    if weekly is not None:
        prompt_parts.append(
            "LATEST WEEKLY DIGEST (%s — %s):\n%s"
            % (weekly["period_key"], weekly["title"], weekly["body_md"])
        )
    if picks:
        prompt_parts.append(
            "TOP RECENT CURATIONS (JSON):\n%s"
            % json.dumps([dict(r) for r in picks], indent=1,
                         ensure_ascii=False)
        )

    try:
        out = adapter.complete(
            "deep", SYSTEM_TRENDS, "\n\n".join(prompt_parts), TRENDS_SCHEMA,
            cfg=cfg, conn=conn, cap_kind="daily",
        )
    except (LLMError, SpendCapExceeded) as e:
        db_mod.log_health(conn, "publish", "error", "kb trends LLM: %s" % e)
        print("kb trends failed: %s" % e)
        return None

    new_body = out["trends_md"].strip()
    if _ARCHIVE_RE.search(new_body):  # same breadth as the publish scrub
        db_mod.log_health(conn, "publish", "error",
                          "kb trends cited an archive link — not stored")
        return None
    entry = "- %s: %s" % (datetime.date.today().isoformat(),
                          out["changes"].strip())
    log = entry + ("\n" + old_log if old_log else "")
    content = "%s\n\n%s\n## Changelog\n%s\n" % (
        new_body, _CHANGELOG_MARKER, log)
    return TRENDS_PATH, content
